
import { globalTokens as $ } from "./globalTokens.stylex";
import * as stylex from "@stylexjs/stylex";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body {...stylex.props(styles.body)}>{children}</body>
    </html>
  );
}

const fgColor = `${$.success}`;

const styles = stylex.create({
  body: {
    color: fgColor,
  },
});
